apiVersion: v1
kind: Template

labels:
  application: admin-edge

metadata:
  name: admin-edge

parameters:
  - name: APPLICATION_NAME
    value: admin-edge
    required: true
  - name: CONFIG_MAP_NAME
    value: 2020-demo-common
    required: true
  - name: REPLICAS
    value: "1"
    required: true
  - name: IMAGE_REPOSITORY
    value: quay.io/redhatdemo/2020-admin-edge:latest
    required: true
  - name: CONTAINER_REQUEST_CPU
    value: 300m
  - name: CONTAINER_REQUEST_MEMORY
    value: 400Mi
  - name: CONTAINER_LIMIT_CPU
    value: 500m
  - name: CONTAINER_LIMIT_MEMORY
    value: 1000Mi

objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
    spec:
      replicas: ${{REPLICAS}}
      selector:
        deploymentconfig: ${APPLICATION_NAME}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
            deploymentconfig: ${APPLICATION_NAME}
        spec:
          containers:
            - envFrom:
                - configMapRef:
                    name: ${CONFIG_MAP_NAME}
              image: ${IMAGE_REPOSITORY}
              imagePullPolicy: Always
              name: ${APPLICATION_NAME}
              resources:
                requests:
                  cpu: ${CONTAINER_REQUEST_CPU}
                  memory: ${CONTAINER_REQUEST_MEMORY}
                limits:
                  cpu: ${CONTAINER_LIMIT_CPU}
                  memory: ${CONTAINER_LIMIT_MEMORY}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /etc/messaging/
                  name: skupper
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: skupper
              secret:
                defaultMode: 420
                secretName: skupper
      test: false
      triggers:
        - type: ConfigChange

