apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${APPLICATION_NAME}
    app.kubernetes.io/part-of: leaderboard-aggregator
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
        topic: ${KAFKA_STREAMS_TOPIC}
    spec:
      containers:
        - image: quay.io/redhatdemo/2020-leaderboard-aggregator
          imagePullPolicy: Always
          name: aggregator
          env:
            - name: QUARKUS_KAFKA_STREAMS_APPLICATION_ID
              value: ${APPLICATION_NAME}
            - name: QUARKUS_KAFKA_STREAMS_TOPICS
              value: ${KAFKA_STREAMS_TOPIC}
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: openshift-pgsql12-primary-secret
                  key: database-username
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openshift-pgsql12-primary-secret
                  key: database-username-password
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          #Smallrye health checks has issue here
          # livenessProbe:
          #   httpGet:
          #     path: /health/live
          #     port: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /health/ready
          #     port: 8080
          resources:
            requests:
              cpu: "400m"
              memory: "500Mi"
            limits:
              cpu: "600m"
              memory: "1Gi"
