apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: leaderboard-messaging
    app.kubernetes.io/part-of: leaderboard-messaging
  name: leaderboard-messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaderboard-messaging
  template:
    metadata:
      labels:
        app: leaderboard-messaging
    spec:
      containers:
        - image: quay.io/redhatdemo/2020-leaderboard-messaging
          imagePullPolicy: Always
          name: messaging
          env:
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: openshift-pgsql12-primary-secret
                  key: database-username
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openshift-pgsql12-primary-secret
                  key: database-username-password
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          #Smallrye health checks has issue here
          # livenessProbe:
          #   httpGet:
          #     path: /health/live
          #     port: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /health/ready
          #     port: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "500Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - mountPath: /etc/messaging
              name: skupper-amqp-trust
      volumes:
        - name: skupper-amqp-trust
          secret:
            secretName: skupper
