---
apiVersion: batch/v1
kind: Job
metadata:
  name: leaderboard-schema
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      volumes:
        - name: leaderboard-schema
          configMap:
            name: leaderboard-schema
            items:
              - key: schema.sql
                path: schemas/schema.sql
      containers:
        - name: pgsql12-client
          image: quay.io/rhdevelopers/openshift-pgsql12-primary:centos7-clients
          imagePullPolicy: Always
          env:
            - name: PGHOST
              value: postgresql
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: openshift-pgsql12-primary-secret
                  key: database-db
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: openshift-pgsql12-primary-secret
                  key: database-username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: openshift-pgsql12-primary-secret
                  key: database-username-password
          command: ["/usr/pgsql-12/bin/psql"]
          args:
            [
              "--dbname=$(PGDATABASE)",
              "--file=/opt/sql/schemas/schema.sql",
              "--no-password",
            ]
          volumeMounts:
            - name: leaderboard-schema
              mountPath: /opt/sql
      restartPolicy: Never
  backoffLimit: 1
