apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: datagrid-service
metadata:
  labels:
    template: datagrid-service
  name: datagrid-service
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        application: datagrid-service
      name: datagrid-ping
    spec:
      clusterIP: None
      ports:
      - name: ping
        port: 7800
        protocol: TCP
        targetPort: 7800
      selector:
        deploymentConfig: datagrid-service
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        application: datagrid-service
      name: datagrid-service
    spec:
      ports:
      - name: single-port
        port: 11222
        targetPort: 11222
      selector:
        deploymentConfig: datagrid-service
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      labels:
        application: datagrid-service
      name: datagrid-service
    spec:
      replicas: ${{NUMBER_OF_INSTANCES}}
      serviceName: datagrid-ping
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 20
          intervalSeconds: 20
          timeoutSeconds: 1200
          maxUnavailable: 1
          maxSurge: 1
      selector:
        matchLabels:
          application: datagrid-service
          deploymentConfig: datagrid-service
      template:
        metadata:
          labels:
            application: datagrid-service
            deploymentConfig: datagrid-service
          name: datagrid-service
        spec:
          containers:
          - env:
            - name: USER
              value: lnd1-ffm1
            - name: PASS
              value: lnd1-ffm1
            - name: CONFIG_PATH
              value: /config/server.yaml
            image: quay.io/infinispan/server:10.1.3.Final
            name: datagrid-service
            ports:
            - containerPort: 7800
              name: ping
              protocol: TCP
            - containerPort: 11222
              name: hotrod
              protocol: TCP
            livenessProbe:
              httpGet:
                path: /rest/v2/cache-managers/default/health/status
                port: 11222
              failureThreshold: 5
              initialDelaySeconds: 10
              successThreshold: 1
              timeoutSeconds: 10
            readinessProbe:
              httpGet:
                path: /rest/v2/cache-managers/default/health/status
                port: 11222
              failureThreshold: 5
              initialDelaySeconds: 10
              successThreshold: 1
              timeoutSeconds: 10
            resources:
              limits:
                memory: 2048Mi
              requests:
                cpu: "0.5"
                memory: 2048Mi
            volumeMounts:
            - mountPath: /config
              name: config-volume
          volumes:
            - name: config-volume
              configMap:
                name: datagrid-configuration
parameters:
- description: Specifies how many instances of the application to create in the cluster.
  displayName: Number of Instances
  name: NUMBER_OF_INSTANCES
  required: true
  value: "2"